apiVersion: apps/v1
kind: Deployment
metadata:
  name:  goods-api
  annotations:
    "sidecar.jaegertracing.io/inject": "true" # <1>
  namespace: default
spec:
  replicas: 3  # expected pods
  selector:  # Label Selector，必须匹配 Pod 模板中的标签
    matchLabels:
      app: goods-api
  template:  # Pod 模板
    metadata:
      labels:
        app: goods-api
    spec:
      containers:
        - name: goods-api
          image: gcr.io/nth-pottery-317206/goods_api
          ports:
            - containerPort: 10090
---
apiVersion: v1
kind: Service
metadata:
  name: goods-api
spec:
  selector:
    app: goods-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 10090